ingressController:
  enabled: true
  installCRDs: true

proxy:
  type: LoadBalancer
  http:
    enabled: true
    servicePort: 80
  tls:
    enabled: false

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
